name: Run Tests and Publish Allure Report to GitHub Pages

on:
  push:
    branches:
      - main # меняйте на вашу основную ветку
  pull_request:
    types: [opened, synchronize]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with Allure report generation
        run: |
          pytest --alluredir=./allure-report

      - name: Generate Allure HTML report
        run: |
          allure generate ./allure-report -o ./html-report --clean

      - name: Deploy generated reports to GitHub Pages
        if: github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, '[skip ci]')
        uses: peaceiris/actions-gh-pages@v3
        env:
          PUBLISH_BRANCH: gh-pages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          deploy_dir: html-report